// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetCtx():Promise<context.Context>;

export function SaveJar():Promise<void>;

export function SelectFile():Promise<void>;

export function TranslateJar():Promise<void>;
