// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCtx() {
  return window['go']['main']['App']['GetCtx']();
}

export function SaveJar() {
  return window['go']['main']['App']['SaveJar']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function TranslateJar() {
  return window['go']['main']['App']['TranslateJar']();
}
